dpi-aware=no
icon-theme=Papirus-Dark
width=60

font=JetBrains Mono:weight=medium:size=13
#line-height=28

fields=name,generic,comment,categories,filename,keywords

terminal=konsole
prompt=">  "

show-actions=yes
exit-on-keyboard-focus-loss=no
fuzzy=yes

[colors]
background=282a36fa
selection=3d4474fa
border=fffffffa
text=f8f8f2ff
match=8be9fdff
selection-text=ffffffff

[border]
radius=20
width=2

[dmenu]
exit-immediately-if-empty=yes
